<template>
    <!-- content begin -->
    <section>
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb pt-5 mb-5">
          <li class="breadcrumb-item"><router-link class="text-primary" to="/">Home</router-link></li>
          <li class="breadcrumb-item active" aria-current="page">Technology</li>
        </ol>
      </nav>
      <div class="row">
        <div class="col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/rZ_KatO4sJg" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  WATERPROOF BREATHABLE
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>Trueway waterproof & Breathable fabrics block wind and water on the
                    outside while allowing water vapor generated by your body to escape – keeping you warm, dry and
                    comfortable. They are with laminated constructions, refer to 2 layer, 2.5 layer or 3 layer construction.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/zzfLdR6ZFGc" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                  WATERPROOF REPELLENCY
                </button>
              </h2>
              <div id="collapseTwo" class="accordion-collapse collapse " aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>Water repellent fabrics are processed with water repellent additives.
                    The water droplets form on the surface but do not penetrate the fabric and allowing for the moisture
                    drops to roll off easily. This keeps the surface of the fabric clean and enables the fabric to
                    “breathe”. The efficiency of water repellent characteristics can be temporary or durable depending on
                    the chemical and process.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/sQLJnxsjIWU" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                  SUN PROTECTION
                </button>
              </h2>
              <div id="collapseThree" class="accordion-collapse collapse " aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>By using UV-Cut additive during the dyeing process, the fabric can
                    effectively prevent UV penetration. Such textiles act as excellent sunshine shields and protect the
                    human body from unnecessary exposure to sunlight which could cause harm to skin. It has superior color
                    fastness stability and has long lasting sun protection (up to 30+ UPF rating) depending upon fabric
                    construction and color.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/DRF7vzjS85g" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingForth">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseForth" aria-expanded="true" aria-controls="collapseForth">
                  ANTIBACTERIAL
                </button>
              </h2>
              <div id="collapseForth" class="accordion-collapse collapse " aria-labelledby="headingForth" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>Application of chemicals can suppress the growth of harmful bacteria
                    on the fabric and on the human skin. It provides long-lasting performance and enhances comfort and all
                    round well-being.</p>
                </div>
              </div>
            </div>
            </div>

        </div>
        <div class="col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/gR9MTDiX5xs" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingFifth">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFifth" aria-expanded="true" aria-controls="collapseFifth">
                  CHLORINE RESISTANCE
                </button>
              </h2>
              <div id="collapseFifth" class="accordion-collapse collapse " aria-labelledby="headingFifth" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>The Chlorine-Resistant treatment of the fabric happens during the
                    dye-fixing process. It enhances the color fastness to chlorine-bleach and effectively protects the suit
                    from fading. This offers high chlorine-resistance without compromising the elasticity and wearability of
                    the fabric.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class="col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/ddvQmdMdEmE" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingSixth">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSixth" aria-expanded="true" aria-controls="collapseSixth">
                  ANTI-STATIC
                </button>
              </h2>
              <div id="collapseSixth" class="accordion-collapse collapse " aria-labelledby="headingSixth" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>Anti-static treatment can enhance the surface conductivity of the
                    fibers to prevent the build-up of static charge at low humidity. It helps reduce injuries caused by high
                    static to the human body and electronic components when applied to equipment. However, common knitted
                    fabric features such as cleanliness, warmth and comfort are unaffected.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class="col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/dnodIbMul3M" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingSeventh">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSeventh" aria-expanded="true" aria-controls="collapseSeventh">
                  ANTI-ODOR
                </button>
              </h2>
              <div id="collapseSeventh" class="accordion-collapse collapse " aria-labelledby="headingSeventh" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>Trueway's Anti-Odor fabric is fused with activated carbon , which
                    gives fabric ability to absorb smells. For example , Once the smelly molecules have absorb into
                    microporous structure of activated carbon , others won’t smell the stink of sweat.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class=" col-md-4 col-12 mb-5">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" width="100%" height="315"
                src="https://www.youtube.com/embed/cwt-egajp70" title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen ></iframe>
            </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingEighth">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEighth" aria-expanded="true" aria-controls="collapseEighth">
                  FLEECE FINISH
                </button>
              </h2>
              <div id="collapseEighth" class="accordion-collapse collapse " aria-labelledby="headingEighth" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>Fleece Finish provides fabric rich and soft touch , increase heat and
                    warmth retaining ability , especially suit for midlayer.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/iOu5BP53iSw" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingNinth">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNinth" aria-expanded="true" aria-controls="collapseNinth">
                  COOLING EFFECT
                </button>
              </h2>
              <div id="collapseNinth" class="accordion-collapse collapse " aria-labelledby="headingNinth" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>There are two types of ‘cooling effect’finish :First is special
                    mineral powder ,like jade , coated on yarn; it rapidly conducts body heat to outside. The other is
                    xylitol; it absorbs moisture and body heat to make you feel cooler during work out.</p>
                </div>
              </div>
            </div>
            </div>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/3E7jE16K6L8" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingTenth">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTenth" aria-expanded="true" aria-controls="collapseTenth">
                  FLAME RETARDANT
                </button>
              </h2>
              <div id="collapseTenth" class="accordion-collapse collapse " aria-labelledby="headingTenth" data-bs-parent="#accordionExample">
                <div class="accordion-body bg-secondary text-white">
                  <p>Trueway's Anti-flame fabric is knitted by flame-retardant polyester yarn which renders the textile non-flammable or difficult to ignite. The textile remains unaffected by washing or exposure to the sun. In addition to preventing flames from spreading, this textile also keeps its original performance.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/2pHO-7jj7DU" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingElventh">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEleventh" aria-expanded="true" aria-controls="collapseEleventh">
                  TRUE-TI
                </button>
              </h2>
              <div id="collapseEleventh" class="accordion-collapse collapse" aria-labelledby="headingEleventh" data-bs-parent="#accordionExample">
                <div class="accordion-body  bg-secondary text-white">
                  <p>
                    The yarn of True-Ti contains liquid titanium , it can boost blood
                  circulation , increases metabolism and oxygen level , reduces lactic acid and discomfort ,relieves
                  muscle pains , provides more energy , and never be washed out!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/zx_HQpnP2gg" title="YouTube video player" frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen ></iframe>
          </div>
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingTwelve">
                <button class="accordion-button bg-success text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwelve" aria-expanded="true" aria-controls="collapseTwelve">
                  MOISTURE WICKING
                </button>
              </h2>
              <div id="collapseTwelve" class="accordion-collapse collapse" aria-labelledby="headingTwelve" data-bs-parent="#accordionExample">
                <div class="accordion-body  bg-secondary text-white">
                  <p>Moisture wicking finish makes synthetic fabric absorb sweat while
                    transferring to outside rapidly. The sportswear with moisture wicking finish will dry out much faster
                    than cotton clothing , so it especially suit for baselayer.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- content end -->
</template>
