<template>
  <!-- content begin -->
  <section>
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb pt-5 mb-5">
          <li class="breadcrumb-item">
            <router-link class="text-primary" to="/">Home</router-link>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Technology</li>
        </ol>
      </nav>
      <div class="row">
        <div class="col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/rZ_KatO4sJg?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/rZ_KatO4sJg?autoplay=1>
              <img src=https://img.youtube.com/vi/rZ_KatO4sJg/hqdefault.jpg alt='Waterproof Breathable Fabric 防水透濕布料 '><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Waterproof Breathable Fabric 防水透濕布料 "></iframe>
          </div>
          <button @click="isOpenA = !isOpenA" class="border-0 w-100 btn btn-success text-white  py-3">
            WATERPROOF BREATHABLE <i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenA" class="bg-secondary text-white p-3 rounded">
            <p>
              Trueway waterproof & Breathable fabrics block wind and water on the
              outside while allowing water vapor generated by your body to escape – keeping you warm, dry and
              comfortable. They are with laminated constructions, refer to 2 layer, 2.5 layer or 3 layer
              construction.
            </p>
          </div>
          </Transition>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="100%" height="315"
              src="https://www.youtube.com/embed/zzfLdR6ZFGc?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/zzfLdR6ZFGc?autoplay=1>
              <img src=https://img.youtube.com/vi/zzfLdR6ZFGc/hqdefault.jpg alt='Water Repellency treatment 防潑水加工'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Water Repellency treatment 防潑水加工"></iframe>
          </div>
          <button @click="isOpenB = !isOpenB" class="border-0 w-100 btn btn-success text-white py-3">
            WATERPROOF REPELLENCY <i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenB" class="bg-secondary text-white p-3 rounded">
            <p>
              Water repellent fabrics are processed with water repellent additives.
              The water droplets form on the surface but do not penetrate the fabric and allowing for the moisture
              drops to roll off easily. This keeps the surface of the fabric clean and enables the fabric to
              “breathe”. The efficiency of water repellent characteristics can be temporary or durable depending
              on
              the chemical and process.
            </p>
          </div>
          </Transition>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <iframe width="100%" height="315" src="https://www.youtube.com/embed/sQLJnxsjIWU?autoplay=1"
            srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/sQLJnxsjIWU?autoplay=1>
              <img src=https://img.youtube.com/vi/sQLJnxsjIWU/hqdefault.jpg alt='Sun Protection 抗紫外線機能 '><span>▶</span></a>" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
            title="Sun Protection 抗紫外線機能"></iframe>
          <button @click="isOpenC = !isOpenC" class="border-0 w-100 btn btn-success text-white py-3">
            SUN PROTECTION<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
          <div v-show="isOpenC" class="bg-secondary text-white p-3 rounded">
            <p>
              By using UV-Cut additive during the dyeing process, the fabric can
              effectively prevent UV penetration. Such textiles act as excellent sunshine shields and protect the
              human body from unnecessary exposure to sunlight which could cause harm to skin. It has superior
              color
              fastness stability and has long lasting sun protection (up to 30+ UPF rating) depending upon fabric
              construction and color.
            </p>
          </div>
          </Transition>
        </div>
        <div class=" col-md-4 col-12 mb-5">
          <iframe width="100%" height="315" src="https://www.youtube.com/embed/DRF7vzjS85g?autoplay=1"
            srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/DRF7vzjS85g?autoplay=1>
              <img src=https://img.youtube.com/vi/DRF7vzjS85g/hqdefault.jpg alt='Antibacterial Finish 抗菌處理'><span>▶</span></a>" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
            title="Antibacterial Finish 抗菌處理"></iframe>
          <button @click="isOpenD = !isOpenD" class="border-0 w-100 btn btn-success text-white py-3">
            ANTIBACTERIAL<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
          <div v-show="isOpenD" class="bg-secondary text-white p-3 rounded">
            <p>
              Application of chemicals can suppress the growth of harmful bacteria
              on the fabric and on the human skin. It provides long-lasting performance and enhances comfort and
              all round well-being.
            </p>
          </div>
          </Transition>
        </div>
        <div class="col-md-4 col-12 mb-5">
            <iframe width="100%" height="315"
              src="https://www.youtube.com/embed/gR9MTDiX5xs?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/gR9MTDiX5xs?autoplay=1>
              <img src=https://img.youtube.com/vi/gR9MTDiX5xs/hqdefault.jpg alt='Chlorine-Resistant treatment 耐氯處理'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Chlorine-Resistant treatment 耐氯處理"></iframe>
              <button @click="isOpenE = !isOpenE" class="border-0 w-100 btn btn-success text-white py-3">
                CHLORINE RESISTANCE<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
          <div v-show="isOpenE" class="bg-secondary text-white p-3 rounded">
            <p>
              The Chlorine-Resistant treatment of the fabric happens during the dye-fixing process. It enhances the color fastness to chlorine-bleach and effectively protects the
                      suit from fading. This offers high chlorine-resistance without compromising the elasticity and
                      wearability of the fabric.
            </p>
          </div>
          </Transition>
        </div>
        <div class="col-md-4 col-12 mb-5">
            <iframe width="100%" height="315"
              src="https://www.youtube.com/embed/ddvQmdMdEmE?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/ddvQmdMdEmE?autoplay=1>
              <img src=https://img.youtube.com/vi/ddvQmdMdEmE/hqdefault.jpg alt='Anti-Static treatment 抗靜電處理'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Anti-Static treatment 抗靜電處理"></iframe>
              <button @click="isOpenF = !isOpenF" class="border-0 w-100 btn btn-success text-white py-3">
                ANTI-STATIC<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenF" class="bg-secondary text-white p-3 rounded">
            <p>Anti-static treatment can enhance the surface conductivity of the fibers to prevent the build-up of static charge at low humidity. It helps reduce injuries caused by
                      high static to the human body and electronic components when applied to equipment. However, common
                      knitted fabric features such as cleanliness, warmth and comfort are unaffected.</p>
          </div>
          </Transition>
        </div>
        <div class="col-md-4 col-12 mb-5">
            <iframe  width="100%" height="315"
              src="https://www.youtube.com/embed/dnodIbMul3M?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/dnodIbMul3M?autoplay=1>
              <img src=https://img.youtube.com/vi/dnodIbMul3M/hqdefault.jpg alt='Anti-Odor Fabric 消臭布料'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Anti-Odor Fabric 消臭布料"></iframe>
              <button @click="isOpenG = !isOpenG" class="border-0 w-100 btn btn-success text-white py-3">
                ANTI-ODOR<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
          <div v-show="isOpenG" class="bg-secondary text-white p-3 rounded">
            <p>Trueway's Anti-Odor fabric is fused with activated carbon , which
                      gives fabric ability to absorb smells. For example , Once the smelly molecules have absorb into
                      microporous structure of activated carbon , others won’t smell the stink of sweat.</p>
          </div>
          </Transition>
        </div>
        <div class=" col-md-4 col-12 mb-5">
            <iframe  width="100%" height="315"
              src="https://www.youtube.com/embed/cwt-egajp70?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/cwt-egajp70?autoplay=1>
              <img src=https://img.youtube.com/vi/cwt-egajp70/hqdefault.jpg alt='Fleece Finish 磨刷毛處理'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Fleece Finish 磨刷毛處理"></iframe>
              <button @click="isOpenH = !isOpenH" class="border-0 w-100 btn btn-success text-white py-3">
                FLEECE FINISH<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenH" class="bg-secondary text-white p-3 rounded">
            <p>Fleece Finish provides fabric rich and soft touch , increase heat and
                      warmth retaining ability , especially suit for midlayer.</p>
          </div>
          </Transition>
        </div>
        <div class=" col-md-4 col-12 mb-5">
            <iframe width="100%" height="315"
              src="https://www.youtube.com/embed/iOu5BP53iSw?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/iOu5BP53iSw?autoplay=1>
              <img src=https://img.youtube.com/vi/iOu5BP53iSw/hqdefault.jpg alt='Cooling Effect ” finish 涼感加工'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Cooling Effect ” finish 涼感加工"></iframe>
              <button @click="isOpenI = !isOpenI" class="border-0 w-100 btn btn-success text-white py-3">
                COOLING EFFECT<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenI" class="bg-secondary text-white p-3 rounded">
            <p>There are two types of ‘cooling effect’ finish:
            First is special mineral powder ,like jade , coated on yarn; it rapidly conducts body heat to outside. The other is
                xylitol; it absorbs moisture and body heat to make you feel cooler during work out.</p>
          </div>
          </Transition>
        </div>
        <div class=" col-md-4 col-12 mb-5">
            <iframe  width="100%" height="315"
              src="https://www.youtube.com/embed/3E7jE16K6L8?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/3E7jE16K6L8?autoplay=1>
              <img src=https://img.youtube.com/vi/3E7jE16K6L8/hqdefault.jpg alt='Flame Retardant Fabric 難燃布料'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Flame Retardant Fabric 難燃布料"></iframe>
              <button @click="isOpenJ = !isOpenJ" class="border-0 w-100 btn btn-success text-white py-3">
                FLAME RETARDANT<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenJ" class="bg-secondary text-white p-3 rounded">
            <p>Trueway's Anti-flame fabric is knitted by flame-retardant polyester yarn which renders the textile
                      non-flammable or difficult to ignite. The textile remains unaffected by washing or exposure to the
                      sun. In addition to preventing flames from spreading, this textile also keeps its original
                      performance.</p>
          </div>
          </Transition>
        </div>
        <div class="col-md-4 col-12 mb-5">
            <iframe width="100%" height="315"
              src="https://www.youtube.com/embed/2pHO-7jj7DU?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/2pHO-7jj7DU?autoplay=1>
              <img src=https://img.youtube.com/vi/2pHO-7jj7DU/hqdefault.jpg alt='True-Ti by Trueway 液化鈦紗'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="True-Ti by Trueway 液化鈦紗"></iframe>
              <button @click="isOpenK = !isOpenK" class="border-0 w-100 btn btn-success text-white py-3">
                TRUE-TI <i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenK" class="bg-secondary text-white p-3 rounded">
            <p>The yarn of True-Ti contains liquid titanium , it can boost blood
                      circulation , increases metabolism and oxygen level , reduces lactic acid and discomfort ,relieves
                      muscle pains , provides more energy , and never be washed out!</p>
          </div>
          </Transition>
        </div>
        <div class="col-md-4 col-12 mb-5">
            <iframe  width="100%" height="315"
              src="https://www.youtube.com/embed/zx_HQpnP2gg?autoplay=1"
              srcdoc="<style>
              *{padding:0;margin:0;overflow:hidden}
              html,body{height:100%}
              img,span{position:absolute;width:100%;top:0;bottom:0;margin:auto}
              span{height:1.5em;text-align:center;font:48px/1.5 sans-serif;color:white;text-shadow:0 0 0.5em black}
              </style>
              <a href=https://www.youtube.com/embed/zx_HQpnP2gg?autoplay=1>
              <img src=https://img.youtube.com/vi/zx_HQpnP2gg/hqdefault.jpg alt='Moisture Wicking Finish 排汗快乾加工'><span>▶</span></a>" frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
              title="Moisture Wicking Finish 排汗快乾加工"></iframe>
              <button @click="isOpenL = !isOpenL" class="border-0 w-100 btn btn-success text-white py-3">
                MOISTURE WICKING<i class="ms-3 bi bi-caret-down fs-5 align-middle"></i>
          </button>
          <Transition>
            <div v-show="isOpenL" class="bg-secondary text-white p-3 rounded">
            <p>Moisture wicking finish makes synthetic fabric absorb sweat while
                      transferring to outside rapidly. The sportswear with moisture wicking finish will dry out much
                      faster
                      than cotton clothing , so it especially suit for baselayer.</p>
          </div>
          </Transition>
        </div>
      </div>
    </div>
  </section>
  <!-- content end -->
  <VueLoading></VueLoading>
</template>

<script>
import VueLoading from '@/components/VueLoading.vue'
export default {
  data () {
    return {
      isOpenA: false,
      isOpenB: false,
      isOpenC: false,
      isOpenD: false,
      isOpenE: false,
      isOpenF: false,
      isOpenG: false,
      isOpenH: false,
      isOpenI: false,
      isOpenJ: false,
      isOpenK: false,
      isOpenL: false
    }
  },
  components: {
    VueLoading
  }
}
</script>

<style lang="scss">
.v-enter-active,
.v-leave-active {
  transition: opacity 0.3s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>
