<template>
  <div>
    <LoadingVue v-model:active.sync="isLoading" :can-cancel="true" :is-full-page="false" class="bg-loading">
      <div class="loadingio-spinner-spin-0fvhe4eftgic">
        <div class="ldio-g6u0b2mnq3v">
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
        </div>
      </div>
    </LoadingVue>
  </div>
</template>

<script>
export default {
  data () {
    return {
      isLoading: true
    }
  },
  mounted () {
    setTimeout(() => {
      this.isLoading = false
    }, 500)
  }
}
</script>

<style lang="scss">
.bg-loading{
  background-color:rgba(0, 163, 224, .3);
}
@keyframes ldio-g6u0b2mnq3v {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5,1.5);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-g6u0b2mnq3v div > div {
  position: absolute;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: #00a3e0;
  animation: ldio-g6u0b2mnq3v 1.2987012987012987s linear infinite;
}.ldio-g6u0b2mnq3v div:nth-child(1) > div {
  left: 148px;
  top: 88px;
  animation-delay: -1.1363636363636362s;
}
.ldio-g6u0b2mnq3v > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 160px 100px;
}.ldio-g6u0b2mnq3v div:nth-child(2) > div {
  left: 130px;
  top: 130px;
  animation-delay: -0.974025974025974s;
}
.ldio-g6u0b2mnq3v > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 142px 142px;
}.ldio-g6u0b2mnq3v div:nth-child(3) > div {
  left: 88px;
  top: 148px;
  animation-delay: -0.8116883116883117s;
}
.ldio-g6u0b2mnq3v > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 100px 160px;
}.ldio-g6u0b2mnq3v div:nth-child(4) > div {
  left: 46px;
  top: 130px;
  animation-delay: -0.6493506493506493s;
}
.ldio-g6u0b2mnq3v > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 58px 142px;
}.ldio-g6u0b2mnq3v div:nth-child(5) > div {
  left: 28px;
  top: 88px;
  animation-delay: -0.487012987012987s;
}
.ldio-g6u0b2mnq3v > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 40px 100px;
}.ldio-g6u0b2mnq3v div:nth-child(6) > div {
  left: 46px;
  top: 46px;
  animation-delay: -0.3246753246753247s;
}
.ldio-g6u0b2mnq3v > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 58px 58px;
}.ldio-g6u0b2mnq3v div:nth-child(7) > div {
  left: 88px;
  top: 28px;
  animation-delay: -0.16233766233766234s;
}
.ldio-g6u0b2mnq3v > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 100px 40px;
}.ldio-g6u0b2mnq3v div:nth-child(8) > div {
  left: 130px;
  top: 46px;
  animation-delay: 0s;
}
.ldio-g6u0b2mnq3v > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 142px 58px;
}
.loadingio-spinner-spin-0fvhe4eftgic {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-g6u0b2mnq3v {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-g6u0b2mnq3v div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
